name: flutter_structure
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  dio:
  http:
  intl:
  logger:
  url_launcher:
  flutter_native_splash:
  flutter_bloc:
  bloc:
  bloc_concurrency:
  flutter_form_bloc:

  freezed_annotation:
  json_annotation:
  dartz:
  infinite_scroll_pagination:
  uuid:

  get_it:
  injectable:
  get_storage: ^2.1.1
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  connectivity_plus:
  shared_preferences:
  share_plus:
  flutter_html:
  path_provider:
  email_validator:
  google_maps_flutter:
  maps_launcher:
  geolocator:
  line_awesome_flutter:
  flutter_svg: 2.0.5
  cached_network_image:
  smooth_page_indicator:
  pinput: ^5.0.0
  go_router: ^14.2.7
  hive:
  hive_flutter:
  flutter_flavorizr: ^2.2.3

  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  build_runner:
  freezed:
  json_serializable:
  hive_generator:

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/fonts/
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
