import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our main.dart with the code generated by Freezed
part 'exceptions.freezed.dart';
part 'exceptions.g.dart';

@freezed
class APIException with _$APIException {
  const factory APIException({
    required String message,
    required int statusCode,
  }) = _APIException;

  factory APIException.fromJson(Map<String, Object?> json) => _$APIExceptionFromJson(json);
}
